### ISSUE TITLE
Tomcat 8.5.16 Error while starting 

### ISSUE THREAD

**Issue by aminweb007** [hazelcast/hazelcast-tomcat-sessionmanager#29]
I followed the steps to run hazelcast with my tomcat 8.5.16 in P2P mode, once I changed server.xml, tomcat doesn't start anymore 

My configue : 
```
<Server>
...
  <!-- hazelcast listener -->
  <Listener className="com.hazelcast.session.P2PLifecycleListener"/>
...
      <Cluster className="org.apache.catalina.ha.tcp.SimpleTcpCluster"
                 channelSendOptions="8">

			<Manager className="com.hazelcast.session.HazelcastSessionManager"/>

...
</Cluster>

....
</Server>
```

PS : with "DeltaManager", tomcat cluster works.

The error I get is :  

```
24-Jul-2017 17:06:37.046 GRAVE [main] org.apache.tomcat.util.digester.Digester.endElement End event threw exception
 java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.IntrospectionUtils.callMethod1(IntrospectionUtils.java:377)
	at org.apache.tomcat.util.digester.SetNextRule.end(SetNextRule.java:145)
	at org.apache.tomcat.util.digester.Digester.endElement(Digester.java:971)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1472)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:579)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:630)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:311)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:494)

24-Jul-2017 17:06:37.052 AVERTISSEMENT [main] org.apache.catalina.startup.Catalina.load Catalina.start using conf/server.xml: Error at (142, 72) : argument type mismatch
24-Jul-2017 17:06:37.055 GRAVE [main] org.apache.tomcat.util.digester.Digester.endElement End event threw exception
 java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.IntrospectionUtils.callMethod1(IntrospectionUtils.java:377)
	at org.apache.tomcat.util.digester.SetNextRule.end(SetNextRule.java:145)
	at org.apache.tomcat.util.digester.Digester.endElement(Digester.java:971)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1472)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:579)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:644)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)

24-Jul-2017 17:06:37.056 AVERTISSEMENT [main] org.apache.catalina.startup.Catalina.load Catalina.start using conf/server.xml: Error at (142, 72) : argument type mismatch
24-Jul-2017 17:06:37.057 GRAVE [main] org.apache.catalina.startup.Catalina.start Cannot start server. Server instance is not configured.

```

**Comment by asdbll** [comment]
Hi @aminweb007 ,
You should put the `<Manager>` element into the `$CATALINA_HOME$/conf/context.xml`file.

**Comment by aminweb007** [comment]
Thanks @asdbll it works :)

**Comment by mesutcelik** [comment]
Hi @aminweb007 ,
very good to see it is working!

**Comment by ajkarloss** [comment]
I am new to Tomcat and related things. Could you explain more about <Manager> element? I see the context.xml file. What exactly should I do?

**Comment by dadde1** [comment]
I have the same problem on tomcat 9. I hope you can help me!
server.xml:
```
    <Listener className="com.hazelcast.session.P2PLifecycleListener"/>
    <Engine name="Catalina" defaultHost="localhost" jvmRoute="tomcat-1">
      <Cluster className="org.apache.catalina.ha.tcp.SimpleTcpCluster" channelSendOptions="8">
          <Manager className="com.hazelcast.session.HazelcastSessionManager" />
....
```

context.xml:
```
<Context>
   <Manager pathname="" classname="com.hazelcast.session.HazelcastSessionManager"/>
</Context>
```

I get the following error on tomcat9:
```
28-Feb-2020 16:30:42.202 WARNING [main] org.apache.catalina.startup.Catalina.load Unable to load server configuration from [/opt/apache-tomcat-9.0.31/conf/server.xml]
        org.xml.sax.SAXParseException; systemId: file:/opt/apache-tomcat-9.0.31/conf/server.xml; lineNumber: 145; columnNumber: 80; Error at line [145] column [80]: [argument type mismatch]
                at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:1892)
                at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:1924)
                at org.apache.tomcat.util.digester.Digester.endElement(Digester.java:983)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:184)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1386)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2725)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
                at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
                at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1468)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:566)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:607)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:567)
                at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:303)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
        Caused by: java.lang.IllegalArgumentException: argument type mismatch
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:567)
                at org.apache.tomcat.util.IntrospectionUtils.callMethod1(IntrospectionUtils.java:380)
                at org.apache.tomcat.util.digester.SetNextRule.end(SetNextRule.java:145)
                at org.apache.tomcat.util.digester.Digester.endElement(Digester.java:980)
                ... 20 more
```

**Comment by alparslanavci** [comment]
Hi @dadde1, can you please remove `<Manager className="com.hazelcast.session.HazelcastSessionManager" />` tag from your `server.xml` and try it again?

**Comment by dadde1** [comment]
Hi alparslanavci, thanks for your reply.
Now it works well
catalina.out:
```
**28-Feb-2020 17:46:46.778 INFO [main] com.hazelcast.config.UrlXmlConfig.null Configuring Hazelcast from 'jar:file:/opt/apache-tomcat-9.0.31/lib/hazelcast-all-4.0.jar!/hazelcast-default.xml'.**
...
28-Feb-2020 17:46:47.017 INFO [main] org.apache.catalina.ha.tcp.SimpleTcpCluster.startInternal Cluster is about to start
28-Feb-2020 17:46:47.022 INFO [main] org.apache.catalina.tribes.transport.ReceiverBase.bind Receiver Server Socket bound to:[/192.168.1.10:4000]
...
```
